# Define services

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  forensic_api:
    build: ../src
    container_name: forensic_api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  process_data:
    build: ../src
    container_name: process_data
    depends_on:
      - mongodb

  query_data:
    build: ../src
    container_name: query_data
    depends_on:
      - mongodb

  insert_data:
    build: ../src
    container_name: insert_data
    depends_on:
      - mongodb

# Define volumes

volumes:
  mongodb_data:
