services:
  postgres:
    image: postgres:14
    container_name: return_to_base_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - ./01-postgres-init.sql:/docker-entrypoint-initdb.d/01-postgres-init.sql:ro
      - ./02-create-tables.sql:/docker-entrypoint-initdb.d/02-create-tables.sql:ro
      - ./03-classification-rules.sql:/docker-entrypoint-initdb.d/03-classification-rules.sql:ro
      - ./04-insert-data.sql:/docker-entrypoint-initdb.d/04-insert-data.sql:ro
      - ./05-case-retrieval.sql:/docker-entrypoint-initdb.d/05-case-retrieval.sql:ro
      - ./06-threat-classification.sql:/docker-entrypoint-initdb.d/06-threat-classification.sql:ro

volumes:
  postgres-data: